export enum OptionColumns {
  SYMBOL = 'symbol',
  STRIKE_PRICE = 'strike',
  OPTION_TYPE = 'type',
  PRICE = 'price',
  DAY_CHANGE_PERCENT = 'price_change',
  VOLUME = 'volume',
  VOLUME_CHANGE_PERCENT = 'volume_change',
  TTV = 'ttv',
  OI = 'oi',
  OI_CHANGE_PERCENT = 'oi_change',
  BASIS = 'basis',
  SPOT = 'spot',
  BUILD_UP = 'build_up',
  IV = 'iv',
  IV_CHANGE_PERCENT = 'iv_change',
  DELTA = 'delta',
  GAMMA = 'gamma',
  RHO = 'rho',
  THETA = 'theta',
  VEGA = 'vega',
}
